export type Language = "es" | "en" | "pt";

export const languages: { code: Language; label: string }[] = [
  { code: "es", label: "Español" },
  { code: "en", label: "English" },
  { code: "pt", label: "Português" },
];

export const translations = {
  es: { todaysMatches: "Partidos de hoy", previous: "Anterior", next: "Siguiente", today: "Hoy", all: "Todos", live: "En vivo", upcoming: "Próximo", finished: "Finalizado", competitions: "Competiciones", events: "Eventos", statistics: "Estadísticas", lineups: "Alineaciones", standings: "Tabla", matchTicker: "Match ticker", fullTime: "Finalizado", demoData: "Datos demo", language: "Idioma", theme: "Tema", dark: "Oscuro", light: "Claro", matches: "partidos", match: "partido", kickoff: "Inicio", score: "Marcador", dateTime: "Fecha y hora", stadium: "Estadio", status: "Estado", backToMatches: "Volver a partidos", matchSections: "Secciones del partido", minuteByMinute: "Minuto a minuto", matchEvents: "Eventos del partido", performance: "Rendimiento", mainStats: "Estadísticas principales", squads: "Planteles", confirmedLineups: "Alineaciones confirmadas", context: "Contexto", tablePositions: "Tabla de posiciones", startingEleven: "Once inicial", matchComparison: "Comparativa del partido", detail: "Detalle", team: "Equipo", noMockEvents: "Sin eventos demo para este partido.", noMockStats: "Sin estadísticas demo para este partido.", noMockLineups: "Sin alineaciones demo para este partido." },
  en: { todaysMatches: "Today's matches", previous: "Previous", next: "Next", today: "Today", all: "All", live: "Live", upcoming: "Upcoming", finished: "Finished", competitions: "Competitions", events: "Events", statistics: "Statistics", lineups: "Lineups", standings: "Standings", matchTicker: "Match ticker", fullTime: "Full time", demoData: "Demo data", language: "Language", theme: "Theme", dark: "Dark", light: "Light", matches: "matches", match: "match", kickoff: "Kickoff", score: "Score", dateTime: "Date and time", stadium: "Stadium", status: "Status", backToMatches: "Back to matches", matchSections: "Match sections", minuteByMinute: "Minute by minute", matchEvents: "Match events", performance: "Performance", mainStats: "Main statistics", squads: "Squads", confirmedLineups: "Confirmed lineups", context: "Context", tablePositions: "Standings", startingEleven: "Starting eleven", matchComparison: "Match comparison", detail: "Detail", team: "Team", noMockEvents: "No demo events for this match.", noMockStats: "No demo statistics for this match.", noMockLineups: "No demo lineups for this match." },
  pt: { todaysMatches: "Jogos de hoje", previous: "Anterior", next: "Próximo", today: "Hoje", all: "Todos", live: "Ao vivo", upcoming: "Próximos", finished: "Encerrados", competitions: "Competições", events: "Eventos", statistics: "Estatísticas", lineups: "Escalações", standings: "Classificação", matchTicker: "Ticker de jogos", fullTime: "Fim de jogo", demoData: "Dados demo", language: "Idioma", theme: "Tema", dark: "Escuro", light: "Claro", matches: "jogos", match: "jogo", kickoff: "Início", score: "Placar", dateTime: "Data e hora", stadium: "Estádio", status: "Status", backToMatches: "Voltar aos jogos", matchSections: "Seções do jogo", minuteByMinute: "Minuto a minuto", matchEvents: "Eventos do jogo", performance: "Desempenho", mainStats: "Estatísticas principais", squads: "Elencos", confirmedLineups: "Escalações confirmadas", context: "Contexto", tablePositions: "Classificação", startingEleven: "Onze inicial", matchComparison: "Comparativo do jogo", detail: "Detalhe", team: "Equipe", noMockEvents: "Sem eventos demo para este jogo.", noMockStats: "Sem estatísticas demo para este jogo.", noMockLineups: "Sem escalações demo para este jogo." },
} as const;

export type TranslationKey = keyof typeof translations.es;
